# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='last_login',
        ),
    ]
