# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_polls', '0002_remove_loginuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
